name       : freetype2
version    : 2.10.1
release    : 27
source     :
    - https://download.savannah.gnu.org/releases/freetype/freetype-2.10.1.tar.gz : 3a60d391fd579440561bf0e7f31af2222bc610ad6ce4d9d7bd2165bca8669110
license    : GPL-2.0-or-later
summary    : Font rendering library
component  : desktop.library
description: |
    The FreeType2 package contains a library which allows applications to properly render TrueType fonts.
patterns   :
    - devel :
        - /usr/bin/freetype-config
        - /usr/share/man/man1
        - /usr/share/aclocal
    - subpixel : /usr/share/fonts/enable_subpixel_rendering
builddeps  :
    - pkgconfig32(harfbuzz)
    - pkgconfig32(libpng)
    - pkgconfig32(zlib)
    - bzip2-devel
autodep    : false
rundeps    :
    - glibc
    - libpng
    - zlib
    - 32bit :
        - freetype2
        - glibc-32bit
        - libpng-32bit
        - zlib-32bit
    - devel :
        - freetype2
        - zlib-devel
        - libpng-devel
        - harfbuzz-devel
    - 32bit-devel :
        - freetype2-32bit
        - zlib-32bit-devel
        - libpng-32bit-devel
        - harfbuzz-32bit-devel
    - subpixel :
        - freetype2
emul32     : yes
optimize   : speed
setup      : |
    %apply_patches
    %configure --disable-static \
            --enable-freetype-config
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 $installdir/usr/share/fonts
    echo "The presence of this file will enable subpixel rendering globally" > $installdir/usr/share/fonts/enable_subpixel_rendering
