name       : freetype2
version    : 2.7.1
release    : 14
source     :
    - http://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.gz : 162ef25aa64480b1189cdb261228e6c5c44f212aac4b4621e28cf2157efb59f5
license    : GPL-3.0
summary    : Font rendering library
component  : system.base
description: |
    The FreeType2 package contains a library which allows applications to properly render TrueType fonts.
patterns   :
    - devel : /usr/share/aclocal
    - subpixel : /usr/share/fonts/enable_subpixel_rendering
builddeps  :
    - pkgconfig32(zlib)
rundeps    :
    - subpixel :
        - freetype2
emul32     : yes
optimize   : speed
setup      : |
    %patch -p1 < $pkgfiles/0001-modules-Enable-gxvalid-otvalid.patch
    %patch -p1 < $pkgfiles/0002-config-Enabel-subpixel-rendering-infinality-engine.patch
    %patch -p1 < $pkgfiles/0003-truetype-Only-enable-subpixel-rendering-when-a-speci.patch
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    %make clean
    install -D -d -m 00755 $installdir/usr/share/fonts
    echo "The presence of this file will enable subpixel rendering globally" > $installdir/usr/share/fonts/enable_subpixel_rendering
