name       : freetype2
version    : 2.7
release    : 13
source     :
    - http://download.savannah.gnu.org/releases/freetype/freetype-2.7.tar.gz : 7b657d5f872b0ab56461f3bd310bd1c5ec64619bd15f0d8e08282d494d9cfea4
license    : GPL-3.0
summary    : Font rendering library
component  : system.base
description: |
    The FreeType2 package contains a library which allows applications to properly render TrueType fonts.
patterns   :
    - devel : /usr/share/aclocal
    - subpixel : /usr/share/fonts/enable_subpixel_rendering
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - pkgconfig32(zlib)
rundeps    :
    - subpixel :
        - freetype2
emul32     : yes
optimize   : speed
setup      : |
    %patch -p1 < $pkgfiles/0001-modules-Enable-gxvalid-otvalid.patch
    %patch -p1 < $pkgfiles/0002-config-Enabel-subpixel-rendering-infinality-engine.patch
    %patch -p1 < $pkgfiles/0003-truetype-Only-enable-subpixel-rendering-when-a-speci.patch
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    %make clean
    install -D -d -m 00755 $installdir/usr/share/fonts
    echo "The presence of this file will enable subpixel rendering globally" > $installdir/usr/share/fonts/enable_subpixel_rendering
