name       : freetype2
version    : 2.8
release    : 16
source     :
    - https://download.savannah.gnu.org/releases/freetype/freetype-2.8.tar.gz : 33a28fabac471891d0523033e99c0005b95e5618dc8ffa7fa47f9dadcacb1c9b
license    : GPL-3.0
summary    : Font rendering library
component  : desktop.library
description: |
    The FreeType2 package contains a library which allows applications to properly render TrueType fonts.
patterns   :
    - devel : /usr/share/aclocal
    - subpixel : /usr/share/fonts/enable_subpixel_rendering
builddeps  :
    - pkgconfig32(harfbuzz)
    - pkgconfig32(libpng)
    - pkgconfig32(zlib)
rundeps    :
    - subpixel :
        - freetype2
emul32     : yes
optimize   : speed
setup      : |
    %apply_patches
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    %make clean
    install -D -d -m 00755 $installdir/usr/share/fonts
    echo "The presence of this file will enable subpixel rendering globally" > $installdir/usr/share/fonts/enable_subpixel_rendering
