name       : freetype2
version    : 2.13.0
release    : 33
source     :
    - http://download.savannah.nongnu.org/releases/freetype/freetype-2.13.0.tar.xz : 5ee23abd047636c24b2d43c6625dcafc66661d1aca64dec9e0d05df29592624c
homepage   : https://freetype.org/
license    : GPL-2.0-or-later
component  :
    - desktop.library
    - subpixel : desktop.library
summary    : Font rendering library
description: |
    The FreeType2 package contains a library which allows applications to properly render TrueType fonts.
patterns   :
    - devel :
        - /usr/bin/freetype-config
        - /usr/share/man/man1
        - /usr/share/aclocal
    - subpixel : /usr/share/fonts/enable_subpixel_rendering
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(libbrotlicommon)
    - bzip2-32bit-devel
autodep    : false
rundeps    :
    - brotli
    - bzip2
    - glibc
    - libpng
    - zlib
    - 32bit :
        - brotli-32bit
        - bzip2-32bit
        - freetype2
        - glibc-32bit
        - libpng-32bit
        - zlib-32bit
    - devel :
        - brotli-devel
        - bzip2-devel
        - freetype2
        - zlib-devel
        - libpng-devel
        - harfbuzz-devel
    - 32bit-devel :
        - brotli-32bit-devel
        - bzip2-32bit-devel
        - freetype2-32bit
        - zlib-32bit-devel
        - libpng-32bit-devel
        - harfbuzz-32bit-devel
    - subpixel :
        - freetype2
emul32     : yes
optimize   : speed
setup      : |
    %apply_patches
    sed 's/%PKG_CONFIG%/pkg-config/g' builds/unix/freetype-config.in > freetype-config
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 builds/unix/freetype2.m4 $installdir/usr/share/aclocal/freetype2.m4
    install -Dm00755 freetype-config $installdir/usr/bin/freetype-config
    install -Dm00644 docs/freetype-config.1 $installdir/usr/share/man/man1/freetype-config.1
    install -dm00755 $installdir/usr/share/fonts
    echo "The presence of this file will enable subpixel rendering globally" > $installdir/usr/share/fonts/enable_subpixel_rendering
