name        : freetype2
version     : 2.6.1
release     : 8
source     :
    - http://savannah.spinellicreations.com/freetype/freetype-2.6.1.tar.bz2 : 2f6e9a7de3ae8e85bdd2fe237e27d868d3ba7a27495e65906455c27722dd1a17
license     : GPL-3.0
summary     : Font rendering library
description : |
    The FreeType2 package contains a library which allows applications to properly render TrueType fonts.
patterns   :
    - devel: /usr/share/aclocal
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - pkgconfig32(zlib)
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/enable-subpixel-rendering.patch
    %patch -p1 < $pkgfiles/enable-gxvalid-otvalid.patch
    %patch -p1 < $pkgfiles/revert_scalable_fonts_metric.patch
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    %make clean
